### ISSUE TITLE
control pitch bend with pc keyboard

### ISSUE THREAD

**Issue by tizi24** [jazz-soft/JZZ-input-Kbd#3]
hello sema! I am looking for a way to use the pitch bend, with the pc keys in real time, my idea is that the path is divided into ten ascii keys

**Comment by jazz-soft** [comment]
Do you want a key press generate a pitch bend signal?
I'll try to implement that in the next version.

**Comment by tizi24** [comment]
> ¿Quiere que una pulsación de tecla genere una señal de inflexión de tono? Intentaré implementar eso en la próxima versión.

exactly! I have thought to divide the pitch bend range into 10 character ascii var map = {48, 49, 50, 51, 52 etc}; with the possibility that if you press 48 and 49 you have an intermediate point to achieve a more fluid range

**Comment by jazz-soft** [comment]
Lo hare pronto :)

**Comment by jazz-soft** [comment]
I made a change for you in the latest version.
It's not documented yet, but you can see the usage example in test.html.
The idea is that now you can assign any function to the key, not just a note.
